variables:
 MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

cache:
 paths:
  - .m2/repository

runtestsandprogram:
 image: maven:3.3.9-jdk-8
 script:
  - cd primes;
    mvn test;
    mvn exec:java
 artifacts:
    name: "${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}_${CI_JOB_ID}_pruefungen"
    expire_in: 8 mos
    paths:
      - "primes/out.txt"
